version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - gochecknoinits
    - gocritic
    - godot
    - gofumpt
    - gosec
    - misspell
    - noctx
    - nolintlint
    - prealloc
    - stylecheck
    - tenv
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G404   # Use of weak random number generator — acceptable in non-security code
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    exhaustive:
      default-signifies-exhaustive: true

issues:
  max-same-issues: 0
  new: false
  fix: false
