version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Baseline
    - govet
    - staticcheck
    - errcheck
    - gosec
    - unused
    - revive
    - cyclop
    - gocritic
    # Optional — error handling
    - nilerr
    - errorlint
    # Optional — context
    - noctx
    - contextcheck
    # Optional — code quality
    - bodyclose
    - dupl
    - dupword
    - makezero
    - nolintlint
    # Optional — performance
    - perfsprint
  settings:
    gosec:
      excludes:
        - G404   # weak PRNG acceptable for non-security token generation
    gocritic:
      enabled-tags:
        - diagnostic
        - style
    cyclop:
      max-complexity: 16
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck

formatters:
  enable:
    - gofumpt

issues:
  max-same-issues: 0
  new: false
  fix: false
